"""add owner company and terminal to lab equipment

Revision ID: 0a1b2c3d4e5f
Revises: 9c0d1e2f3a4b
Create Date: 2026-02-04 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0a1b2c3d4e5f"
down_revision: Union[str, Sequence[str], None] = "9c0d1e2f3a4b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("lab_equipment", sa.Column("owner_company_id", sa.Integer(), nullable=True))
    op.add_column("lab_equipment", sa.Column("terminal_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "fk_lab_equipment_owner_company_id_company",
        "lab_equipment",
        "company",
        ["owner_company_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_lab_equipment_terminal_id_company_terminal",
        "lab_equipment",
        "company_terminal",
        ["terminal_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_lab_equipment_terminal_id_company_terminal",
        "lab_equipment",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_lab_equipment_owner_company_id_company",
        "lab_equipment",
        type_="foreignkey",
    )
    op.drop_column("lab_equipment", "terminal_id")
    op.drop_column("lab_equipment", "owner_company_id")
    # ### end Alembic commands ###
