"""add company id to user

Revision ID: 3c4d5e6f7a8b
Revises: 2b1d3e4f5a6b
Create Date: 2026-02-04 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3c4d5e6f7a8b"
down_revision: Union[str, Sequence[str], None] = "2b1d3e4f5a6b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("company_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "fk_user_company_id_company",
        "user",
        "company",
        ["company_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_user_company_id_company", "user", type_="foreignkey")
    op.drop_column("user", "company_id")
    # ### end Alembic commands ###
