"""add refresh token to user

Revision ID: 76d12d2ab879
Revises: 8553c93e67d5
Create Date: 2026-01-26 16:29:28.577705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76d12d2ab879'
down_revision: Union[str, Sequence[str], None] = '8553c93e67d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('refresh_token_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'refresh_token_hash')
    # ### end Alembic commands ###
