"""equipment type and equipment

Revision ID: e50532f7248f
Revises: 0a1b2c3d4e5f
Create Date: 2026-02-05 10:31:10.951637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e50532f7248f'
down_revision: Union[str, Sequence[str], None] = '0a1b2c3d4e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_type WHERE typname = 'equipmentrole'
            ) THEN
                CREATE TYPE equipmentrole AS ENUM ('reference', 'working');
            END IF;
        END $$;
        """
    )
    op.create_table('equipment_type',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column(
        'role',
        postgresql.ENUM(
            'reference',
            'working',
            name='equipmentrole',
            create_type=False,
        ),
        nullable=False,
    ),
    sa.Column('calibration_days', sa.Integer(), nullable=False),
    sa.Column('verification_days', sa.Integer(), nullable=False),
    sa.Column('maintenance_days', sa.Integer(), nullable=False),
    sa.Column('inspection_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('owner_company_id', sa.Integer(), nullable=False),
    sa.Column('terminal_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['owner_company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['terminal_id'], ['company_terminal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment',
    sa.Column('serial', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('equipment_type_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('owner_company_id', sa.Integer(), nullable=False),
    sa.Column('terminal_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['equipment_type_id'], ['equipment_type.id'], ),
    sa.ForeignKeyConstraint(['owner_company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['terminal_id'], ['company_terminal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment_type_measure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_type_id', sa.Integer(), nullable=False),
    sa.Column(
        'measure',
        postgresql.ENUM(
            'temperature',
            'pressure',
            'length',
            name='equipmentmeasuretype',
            create_type=False,
        ),
        nullable=False,
    ),
    sa.ForeignKeyConstraint(['equipment_type_id'], ['equipment_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment_type_role_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_type_id', sa.Integer(), nullable=False),
    sa.Column(
        'role',
        postgresql.ENUM(
            'reference',
            'working',
            name='equipmentrole',
            create_type=False,
        ),
        nullable=False,
    ),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['equipment_type_id'], ['equipment_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('lab_equipment_measure')
    op.drop_table('lab_equipment')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_equipment_measure',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('equipment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('measure', postgresql.ENUM('temperature', 'pressure', 'length', name='equipmentmeasuretype'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['lab_equipment.id'], name=op.f('lab_equipment_measure_equipment_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('lab_equipment_measure_pkey'))
    )
    op.create_table('lab_equipment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('calibration_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('verification_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('maintenance_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('inspection_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('owner_company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('terminal_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('lab_equipment_company_id_fkey')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], name=op.f('lab_equipment_created_by_user_id_fkey')),
    sa.ForeignKeyConstraint(['owner_company_id'], ['company.id'], name=op.f('fk_lab_equipment_owner_company_id_company')),
    sa.ForeignKeyConstraint(['terminal_id'], ['company_terminal.id'], name=op.f('fk_lab_equipment_terminal_id_company_terminal')),
    sa.PrimaryKeyConstraint('id', name=op.f('lab_equipment_pkey'))
    )
    op.drop_table('equipment_type_role_history')
    op.drop_table('equipment_type_measure')
    op.drop_table('equipment')
    op.drop_table('equipment_type')
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM pg_type WHERE typname = 'equipmentrole'
            ) THEN
                DROP TYPE equipmentrole;
            END IF;
        END $$;
        """
    )
    # ### end Alembic commands ###
